# Generated by Django 2.2.7 on 2019-11-27 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('pimg', models.ImageField(upload_to='')),
                ('brand', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('pname', models.CharField(max_length=20)),
                ('stock', models.IntegerField(default=0)),
                ('stocksold', models.IntegerField(default=0)),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='product registered')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
